### ISSUE TITLE
VBA7 version does not currently work

### ISSUE THREAD

**Issue by fafalone** [fafalone/cTaskDialog64#7]
The method used had previously worked but there appears to be a bug introduced when adapting it to this class. I'm currently investigating.

**Comment by Mo-Lo** [comment]
Your code behind Userform1 in Book1.xlsm might work if you:

1.  comment out zzGetCommonButtonIcon() (Project doesn't compile because of that.)
2.  in code CommandButton1_Click(), replace  " '.ParenthWnd = Me.hWnd " with " .ParenthWnd = 0 "

Thanks.

**Comment by fafalone** [comment]
Yes it appears that function should return a LongPtr() instead, but I haven't seen that error detected by twinBASIC or VBA... it looks to be a runtime error if you actually try to use it. It's not actually called from anywhere. Can you clarify in what scenario you're seeing an error related to this?

And I have indeed tried ParentHwnd = 0, as well as methods for actually obtaining the UserForm hwnd.

**Comment by Mo-Lo** [comment]
I got the error 'Can't assign to an array' when I tried to compile VBAProject.

**Comment by fafalone** [comment]
Ok I see. It should be

```
Public Function zzGetCommonButtonIcon() As LongPtr()
zzGetCommonButtonIcon = icoDataN
End Function
```

I don't get any further compile errors after that.

**Comment by Mo-Lo** [comment]
I got it to work after I used the following code in ShowDialog to populate uTDC_VBA7:
` 
CopyMemory uTDC_VBA7.data(0), cb, 4
CopyMemory uTDC_VBA7.data(4), ByVal VarPtr(uTDC.hWndParent), 8
CopyMemory uTDC_VBA7.data(12), ByVal VarPtr(uTDC.hInstance), 8
CopyMemory uTDC_VBA7.data(20), ByVal VarPtr(uTDC.dwFlags), 4
CopyMemory uTDC_VBA7.data(24), ByVal VarPtr(uTDC.dwCommonButtons), 4
CopyMemory uTDC_VBA7.data(28), ByVal VarPtr(uTDC.pszWindowTitle), 8
CopyMemory uTDC_VBA7.data(36), ByVal VarPtr(uTDC.pszMainIcon), 8
CopyMemory uTDC_VBA7.data(44), ByVal VarPtr(uTDC.pszMainInstruction), 8
CopyMemory uTDC_VBA7.data(52), ByVal VarPtr(uTDC.pszContent), 8
CopyMemory uTDC_VBA7.data(60), ByVal VarPtr(uTDC.cButtons), 4
CopyMemory uTDC_VBA7.data(64), ByVal VarPtr(uTDC.pButtons), 8
CopyMemory uTDC_VBA7.data(72), ByVal VarPtr(uTDC.nDefaultButton), 4
CopyMemory uTDC_VBA7.data(76), ByVal VarPtr(uTDC.cRadioButtons), 4
CopyMemory uTDC_VBA7.data(80), ByVal VarPtr(uTDC.pRadioButtons), 8
CopyMemory uTDC_VBA7.data(88), ByVal VarPtr(uTDC.nDefaultRadioButton), 4
CopyMemory uTDC_VBA7.data(92), ByVal VarPtr(uTDC.pszVerificationText), 8
CopyMemory uTDC_VBA7.data(100), ByVal VarPtr(uTDC.pszExpandedInformation), 8
CopyMemory uTDC_VBA7.data(108), ByVal VarPtr(uTDC.pszExpandedControlText), 8
CopyMemory uTDC_VBA7.data(116), ByVal VarPtr(uTDC.pszCollapsedControlText), 8
CopyMemory uTDC_VBA7.data(124), ByVal VarPtr(uTDC.pszFooterIcon), 8
CopyMemory uTDC_VBA7.data(132), ByVal VarPtr(uTDC.pszFooter), 8
CopyMemory uTDC_VBA7.data(140), ByVal VarPtr(uTDC.pfCallback), 8
CopyMemory uTDC_VBA7.data(148), ByVal VarPtr(uTDC.lpCallbackData), 8
CopyMemory uTDC_VBA7.data(156), ByVal VarPtr(uTDC.CXWidth), 4 

`

**Comment by fafalone** [comment]
That produces a byte-for-byte identical structure as the more compact method. If the callback is set it still crashes for me, if you comment out the callback it works either way.

You can verify this with the CompareMemory api (RtlCompareMemory):

```
    Dim cb As Long
    cb = LenB(uTDC_VBA7)
    Dim udt2 As TASKDIALOGCONFIG_VBA7
    
    CopyMemory udt2.data(0), cb, 4
    CopyMemory udt2.data(4), ByVal VarPtr(uTDC.hWndParent), 60
    CopyMemory udt2.data(64), ByVal VarPtr(uTDC.pButtons), 28
    CopyMemory udt2.data(92), ByVal VarPtr(uTDC.pszVerificationText), 68
CopyMemory uTDC_VBA7.data(0), cb, 4
CopyMemory uTDC_VBA7.data(4), ByVal VarPtr(uTDC.hWndParent), 8
CopyMemory uTDC_VBA7.data(12), ByVal VarPtr(uTDC.hInstance), 8
CopyMemory uTDC_VBA7.data(20), ByVal VarPtr(uTDC.dwFlags), 4
CopyMemory uTDC_VBA7.data(24), ByVal VarPtr(uTDC.dwCommonButtons), 4
CopyMemory uTDC_VBA7.data(28), ByVal VarPtr(uTDC.pszWindowTitle), 8
CopyMemory uTDC_VBA7.data(36), ByVal VarPtr(uTDC.pszMainIcon), 8
CopyMemory uTDC_VBA7.data(44), ByVal VarPtr(uTDC.pszMainInstruction), 8
CopyMemory uTDC_VBA7.data(52), ByVal VarPtr(uTDC.pszContent), 8
CopyMemory uTDC_VBA7.data(60), ByVal VarPtr(uTDC.cButtons), 4
CopyMemory uTDC_VBA7.data(64), ByVal VarPtr(uTDC.pButtons), 8
CopyMemory uTDC_VBA7.data(72), ByVal VarPtr(uTDC.nDefaultButton), 4
CopyMemory uTDC_VBA7.data(76), ByVal VarPtr(uTDC.cRadioButtons), 4
CopyMemory uTDC_VBA7.data(80), ByVal VarPtr(uTDC.pRadioButtons), 8
CopyMemory uTDC_VBA7.data(88), ByVal VarPtr(uTDC.nDefaultRadioButton), 4
CopyMemory uTDC_VBA7.data(92), ByVal VarPtr(uTDC.pszVerificationText), 8
CopyMemory uTDC_VBA7.data(100), ByVal VarPtr(uTDC.pszExpandedInformation), 8
CopyMemory uTDC_VBA7.data(108), ByVal VarPtr(uTDC.pszExpandedControlText), 8
CopyMemory uTDC_VBA7.data(116), ByVal VarPtr(uTDC.pszCollapsedControlText), 8
CopyMemory uTDC_VBA7.data(124), ByVal VarPtr(uTDC.pszFooterIcon), 8
CopyMemory uTDC_VBA7.data(132), ByVal VarPtr(uTDC.pszFooter), 8
CopyMemory uTDC_VBA7.data(140), ByVal VarPtr(uTDC.pfCallback), 8
CopyMemory uTDC_VBA7.data(148), ByVal VarPtr(uTDC.lpCallbackData), 8
CopyMemory uTDC_VBA7.data(156), ByVal VarPtr(uTDC.CXWidth), 4
MsgBox CompareMemory(udt2, uTDC_VBA7, LenB(uTDC_VBA7))
```
It returns 160, meaning all 160 bytes are identical.

**Comment by Mo-Lo** [comment]
Strange. It stopped crashing and the callback is working here.

**Comment by fafalone** [comment]
Weird... would you be able to attach the version you're using where it's working?

**Comment by Mo-Lo** [comment]
Here it is. [Book1.zip](https://github.com/fafalone/cTaskDialog64/files/10255957/Book1.zip)

**Comment by fafalone** [comment]
This issue has finally been resolved.  (Unfortunately the above did not work, with or without the `Stop` and `Sin 0`, and I kinda gave up on the issue). 

Genius VB programmer [The trick](https://github.com/thetrik) has [identified a bug in VBA](https://www.vbforums.com/showthread.php?898424-Class-module-callback-method-crashing-in-VBAx64&p=5618594&viewfull=1#post5618594) regarding initialization of modules in some of the assembly templates backing the p-code interpreter, making it try to execute the callback at an invalid address. (Don't worry, I understand 'invalid address' and 'p-code', that's it too LOL).

Fortunately he also identified an easy workaround: Call an empty dummy sub in `Class_Initialize` that's in the same .bas module as the callback. Doing this in the native VBA code instead of outside API calling it for the first use of the .bas seems to trigger the initialization routine, writing the correct addresses into memory.

This will likely solve this general class of problem, it's not cTaskDialog-specific. 

Please start a new issue for any subsequent problems.
