### ISSUE TITLE
Implemet cTaskDialog64 in MS Access VBA

### ISSUE THREAD

**Issue by DineshLohar** [fafalone/cTaskDialog64#8]
Please tell me how to implemet cTaskDialog64 in MS Access VBA 7 and Which version is successfully working.

**Comment by fafalone** [comment]
For Access at the moment, your best bet is to use Kevin Bell's port of my original VB6 cTaskDialog:

https://accessui.com/Products/VBATaskDialog

Access seems to have some differences that allow that very specific implementation to work, but I've been having a hard time getting that or anything else to work in the rest of Office, and the version in this repo doesn't have the Access-specific version of the class.

**Comment by fafalone** [comment]
Version 1.3.7 should work in Access as well as other Office apps (see: https://github.com/fafalone/cTaskDialog64/issues/7). Please start a new issue if you encounter further problems.
