### ISSUE TITLE
Excel  run-time error 453 Can't find entry point to TaskDialogIndirect in ComCtl32.dll

### ISSUE THREAD

**Issue by N-Gol** [fafalone/cTaskDialog64#9]
Windows 11 64x
Office pro plus 2021 32x

I have imported the classes and enabled the reference to Microsoft Windows Common Controls 6.0 (SP6),
However, it's just showing the error 
 _run-time error 453 Can't find entry point to TaskDialogIndirect in ComCtl32.dll_

it worked for me in Access, so I compered the manifests, and there is an entry in the Access manifest for the common controls, but is missing in the Excel manifest.

	<dependency optional="yes">
		<dependentAssembly>
			<assemblyIdentity type="win32" name="Microsoft.Windows.Common-Controls" version="6.0.1.0" 
                                  publicKeyToken="6595b64144ccf1df" language="*" processorArchitecture="*">
                        </assemblyIdentity>
		</dependentAssembly>
	</dependency>

Seems like Excel is loading by default the common controls version 5.

Is there any other way to load the latest version that does not require the end user to mess with the system files?

**Comment by fafalone** [comment]
First off, "Microsoft Windows Common Controls 6.0 (SP6)"; that's referring to like ListView, TreeView, etc, those controls? That's not required; the requirement is referring to the manifest entry. 

It looks like this is a 32bit thing; 64bit Excel pro plus 21 is definitely fine, but a previous version of 32bit Office I have on a VM is also doing this... obviously inserting it into the manifest is he optimal solution... I'll test if an alternate method by code will work; I use it to create controls with comctl32 visual styles in DLLs where the host app isn't manifested.

**Comment by fafalone** [comment]
Good news, the method I was thinking of works. Requires no modification of any files at all (besides updating cTaskDialog.cls when I post the new release later). 

I just need to test some things because this might impact dpi awareness too since I'm borrowing shell32.dll's manifest which has DPI aware

**Comment by fafalone** [comment]
I've posted cTaskDialog v1.5 which addresses this issue by detecting the lack of comctl6, and if it encounters it, will temporarily activate it via code only for the API call into TaskDialog/TaskDialogIndirect, by using the SxS Activation Context API and borrowing the comctl6-enabled manifest from shell32:

```vba
hActCtx = INVALID_HANDLE_VALUE
If (IsComCtl6 = False) And (useropt_no_force_comctl6 = False) Then
    hShell32 = LoadLibrary("shell32.dll")

    szSys = Environ$("WINDIR") & "\System32"
    Dim ctx As ACTCTX
    ctx.cbSize = LenB(ctx)
    ctx.dwFlags = ACTCTX_FLAG_RESOURCE_NAME_VALID Or ACTCTX_FLAG_ASSEMBLY_DIRECTORY_VALID Or ACTCTX_FLAG_HMODULE_VALID
    ctx.hModule = hShell32
    ctx.lpResourceName = 124
    ctx.lpAssemblyDirectory = StrPtr(szSys)
    hActCtx = CreateActCtx(ctx)
End If
```

```vba
If hActCtx <> INVALID_HANDLE_VALUE Then 'we need to activate comctl32.dll 6.0
    Dim lActCtxCookie As LongPtr
    ActivateActCtx hActCtx, lActCtxCookie
End If
#If (VBA7 <> 0) And (TWINBASIC = 0) And (Win64 <> 0) Then
'Special handling for 64bit VBA7, which doesn't support our manually aligned structure.
'... (omitted from GitHub comment for brevity)
    hr = TaskDialogIndirect_VBA7(uTDC_VBA7, pnButton, pnRadButton, pfVerify)
#Else
hr = TaskDialogIndirect(uTDC, pnButton, pnRadButton, pfVerify)
#End If
If hActCtx <> INVALID_HANDLE_VALUE Then
    DeactivateActCtx 0, lActCtxCookie 'Deactivate, because we don't want to interfere with the rest of the app
End If
```

Then it properly releases it in Class_Terminate.

I didn't test this in Win11 ProPlus 21 specifically, but I did test Excel 2016 32bit and VB6 32bit (no manifest), and the manifest in shell32 was still ok as of Win11 22H2, so it should be good to go. Let me know about any issues.

**Comment by N-Gol** [comment]
I can confirm that it's working now in excel x32 (windows 11 x64) with no need to change the manifest.
Thank you for the quick fix, much appreciated.

**Comment by N-Gol** [comment]
My issue is resolved.
